apiVersion: apps/v1
kind: Deployment
metadata:
  name: bp-recording-app
  labels:
    app: bprecording
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bprecording
  template:
    metadata:
      labels:
        app: bprecording
    spec:
      volumes:
        - name: mongo-secrets
          secret:
            secretName: mongo-secrets
            items:
              - key: MONGO_CREDENTIAL
                path: MONGO_CREDENTIAL
                mode: 0444
      containers:
        - image: ainhabacr.azurecr.io/eadca2/bprecordingservice:v1
          name: bprecordingapp
          imagePullPolicy: Always
          ports:
            - containerPort: 30256
          env:
            - name: PROFILE
              value: "production"
          volumeMounts:
            - name: mongo-secrets
              mountPath: /etc/mongo-secrets
              readOnly: true
